### PR TITLE
Add shortcut to accept defaults

### LINKED ISSUE #41: Create a "fast track" to package option in the cookie
I like the idea of offering both, but I think we should have a short-circuit option up front that asks if you want to use the default settings for everything that doesn't strictly require input.

_Originally posted by @blink1073 in https://github.com/pyOpenSci/pyos-package-template/issues/34#issuecomment-2433386389_

### PR DESCRIPTION
**Pull request by Midnighter**
Fix #41

Implement a question in the template that let's you skip and accept default values. You have an option for the full template and one for the minimal template being created.

I'm definitely creating technical debt here, as the template is made quite a bit more complicated and all the different paths should be tested, but I'm not including any tests 😬. I figure it's the weekend and you might want to use this next week @lwasser.

### CODE REVIEW

**Comment by lwasser** [comment]
hi @Midnighter thank you for this! i'll test it out locally (and let's see what others say). i hear you on the technical debt and will consider that as i play with this - likely tomorrow!

**Comment by blink1073** [comment]
The `no` choice for `use_default` wasn't working, I pushed a fix.  Now all three options LGTM, thanks @Midnighter!

**Review by blink1073 — APPROVED** [review]

**Comment by lwasser** [comment]
@Midnighter given @blink1073 approved please go ahead and merge! I don't want to to be a blocker here!

 We can cut a release and I'll play w it tomorrow after our fall festival sessions are done!!

**Comment by Midnighter** [comment]
Cheers!

**Pull request merged**
