### PR TITLE
Make documentation optional

### LINKED ISSUE #34: The project defaults to using mkdocs for documentation but many in the community use sphinx. Could we have a docs option? sphinx vs mkdocs?
I'm torn between two possibilities:

1. Set up the template only with the sphinx configuration as that is what this community recommends. Limit choices and thereby complexity of using the template.
2. Create different options:
    1. Sphinx
    2. mkdocs
    3. no documentation

### PR DESCRIPTION
**Pull request by Midnighter**
Fix #34

@blink1073 I have started to address the linked issue here. You can see the places where more sphinx configuration will be necessary.

### CODE REVIEW

**Comment by lwasser** [comment]
i just reran ci to see if that fixes things!  it's failing on windows python 3.9 and 3.12

**Comment by Midnighter** [comment]
Hmm, need to look into that.

```
Error: error: invalid path 'template/{% if documentation != "" %}.readthedocs.yaml{% endif %}.jinja'
```

**Comment by Midnighter** [comment]
Ah, found it 🙂 https://copier.readthedocs.io/en/stable/configuring/#conditional-files-and-directories

> On Windows, double-quotes are not valid characters in file and directory paths. This is why we used single-quotes in the example above.

**Review by lwasser — APPROVED** [review]
This looks great to me! CI is now running. i'll cut another release once these two pr's are merged!

**Pull request merged**
